version: '3'
services:
    db:
        container_name: db
        image: postgres:12
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"
            POSTGRES_USER: "postgres"
        ports:
            - 5432:5432
    web:
        build: .
        environment:
            - "SPRING_PROFILES_ACTIVE=dev"
            - "DATABASE_URL=db"
        ports:
            - 8080:8080
        depends_on:
            - db
    selenium-chrome:
        image: selenium/standalone-chrome
        ports:
            - 4444:4444
    e2e:
        build: captain-adhoc-frontend-e2e/
        volumes:
            - ./target:/opt/tests/e2e/target
        command: ./wait-for-it.sh -t 60 selenium-chrome:4444 -- ./wait-for-it.sh -t 60 web:8080 -- ./node_modules/.bin/nightwatch
        depends_on:
          - selenium-chrome
          - web


